services:
  postgres:
    image: postgres:18
    container_name: mediadrop-postgres
    environment:
      POSTGRES_DB: mediadrop
      POSTGRES_USER: mediadrop
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediadrop -d mediadrop"]
      interval: 3s
      timeout: 3s
      retries: 20
volumes:
  pgdata:
